### ISSUE TITLE
Is Client connection threadsafe?

### ISSUE THREAD

**Issue by mengzhuo** [dotcloud/zerorpc-python#113]
I had test on 1000 coroutines  sharing one client,  after all clients connected it will raise RemoteError: Lost heartbeat 10s.

**Comment by bombela** [comment]
A zerorpc client is not thread-safe but it is coroutine/green
thread/greenlet safe, for the purpose of sharing a client and server across
coroutines.

Make sure that your server code is not blocking the process and is gevent
compatible. for example time.sleep will block the process and with it all
the couroutines while gevent.sleep will block the current coroutine only.
That could be the reason your server is not responding for example.

Best,
FX

**Comment by mengzhuo** [comment]
Thanks! 
We find that it's our redis connection is blocking (not monkey patch yet)
